### ISSUE TITLE
Make java client work

### ISSUE THREAD

**Issue by tamalsaha** [tamalsaha/kube-openapi-generator#1]
When you got your OpenAPI spec then you should be able to generate a client using https://github.com/kubernetes-client/gen. After generation you may need to copy the useful utilities from the language repo. For example for python [this is the repo](https://github.com/kubernetes-client/python).

**Comment by tamalsaha** [comment]
ref; https://github.com/kubernetes/kube-openapi/issues/13

**Comment by mbohlool** [comment]
> After generation you may need to copy the useful utilities from the language repo. For example for python this is the repo.

Useful utilities should be in the $lang-base repo. for example for [python](https://github.com/kubernetes-client/python-base)

**Comment by tamalsaha** [comment]
Thanks @mbohlool . Let's continue the conversation in https://github.com/kubernetes-client/gen/issues/59
